Mantas 02 registration
boolean-uk/team-dev-client-c10 pull request #30
Opened 2023-05-22 14:27 UTC by ManNavic

2023-05-22 14:32 UTC, Shylan21 commented
Nice coding, looks good :)

2023-05-22 14:49 UTC, Auenc requested changes

2023-05-22 14:49 UTC, Auenc commented on src/context/auth.js
> +			console.log(storedToken)
Let's remove this console log

2023-05-22 14:49 UTC, Auenc commented on src/pages/register/index.js
> +    console.log(formData.email, formData.password);
Let's remove this console log

2023-05-22 14:49 UTC, Auenc requested changes
Minor changes mentioned in the comments

2023-05-22 14:58 UTC, Auenc submitted a review, later dismissed

2023-05-22 16:33 UTC, Auenc submitted a review, later dismissed

2023-05-22 16:49 UTC, procrastian commented
All good!

2023-05-23 08:46 UTC, JayVith submitted a review, later dismissed
All changes LGTM!

2023-05-23 11:15 UTC, dearshrewdwit requested changes
Only one change - double check it's reasonable.

❗ In future, please don't include in a PR style changes like double quotes to single quotes.
Otherwise everyone's PRs will include these changes going back and from different quotes.

The action here -> 
1. Either agree as a cohort which style to follow, and then enforce it
2. Don't change them

2023-05-23 13:41 UTC, procrastian commented
LGTM

2023-05-23 14:05 UTC, dearshrewdwit approved these changes

2023-05-23 14:12 UTC, procrastian approved these changes
LGTM!

2023-05-23 14:14 UTC, merged