Edit Page - Data of current user added and updated
boolean-uk/team-dev-client-c10 pull request #32
Opened 2023-05-22 15:42 UTC by gid-ctrl

2023-05-22 15:46 UTC, ample-samples requested changes
Works great, just needs a tidy up

2023-05-22 15:46 UTC, ample-samples commented on src/pages/edit/index.js
> +      console.log(userInfo);
Don't need this console.log

2023-05-22 16:02 UTC, ample-samples submitted a review, later dismissed
LGTM

2023-05-23 10:16 UTC, dearshrewdwit submitted a review, later dismissed

2023-05-23 13:28 UTC, ample-samples commented
Added the ability to display the profiles of other users and conditionally render the edit button

2023-05-23 13:31 UTC, ample-samples approved these changes

2023-05-23 13:32 UTC, merged